openapi: '3.0.2'
info:
  title: mundo-verde-app
  version: '1.0'
servers:
  - url: http://localhost:8080/api/v1
paths:
  /categories:
    get:
      responses:
        '200':
          description: OK