openapi: '3.0.2'
info:
  title: mundo-verde-app
  version: '1.0'
servers:
  - url: /api/v1
paths:
  /categories:
    get:
      tags:
        - Store API
      responses:
        '200':
          description: OK